dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.9.1
  share_plus: ^11.1.0
  app_links: ^6.4.1
  url_launcher: ^6.3.2
  file_picker: ^10.3.3
  startapp_sdk: ^1.0.1
