import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

const supabaseProjectRef='gzamivqrrflogjjvhbej';
const supabaseUrl='https://$supabaseProjectRef.supabase.co';
const supabaseKey='sb_publishable_emPACnJ0LsZ1GjParqjJVA_wDO3faQg';
final supabase=Supabase.instance.client;
String authEmailFromPhone(String p)=>'phone_${p.replaceAll(RegExp(r'[^0-9]'),'')}@taskearn.local';

Future<void> main() async{WidgetsFlutterBinding.ensureInitialized();await Supabase.initialize(url:supabaseUrl,publishableKey:supabaseKey);runApp(const AdminApp());}
class AdminApp extends StatelessWidget{const AdminApp({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Task Earn Admin',theme:ThemeData(colorSchemeSeed:Colors.deepPurple,useMaterial3:true),home:supabase.auth.currentSession==null?const AdminLogin():const AdminGate());}
class AdminLogin extends StatefulWidget{const AdminLogin({super.key});@override State<AdminLogin> createState()=>_AdminLoginState();}
class _AdminLoginState extends State<AdminLogin>{final phone=TextEditingController(),pass=TextEditingController();bool loading=false;Future<void> login()async{setState(()=>loading=true);try{await supabase.auth.signInWithPassword(email:authEmailFromPhone(phone.text.trim()),password:pass.text);if(mounted)Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>const AdminGate()),(_)=>false);}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Login failed: $e')));}finally{if(mounted)setState(()=>loading=false);}}@override Widget build(BuildContext c)=>Scaffold(body:SafeArea(child:ListView(padding:const EdgeInsets.all(24),children:[const SizedBox(height:70),const Icon(Icons.admin_panel_settings,size:80),const Center(child:Text('Task Earn Admin',style:TextStyle(fontSize:28,fontWeight:FontWeight.bold))),const SizedBox(height:30),TextField(controller:phone,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'Admin mobile',border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:pass,obscureText:true,decoration:const InputDecoration(labelText:'Password',border:OutlineInputBorder())),const SizedBox(height:16),FilledButton(onPressed:loading?null:login,child:Text(loading?'Checking...':'Admin Login'))])));}
class AdminGate extends StatefulWidget{const AdminGate({super.key});@override State<AdminGate> createState()=>_AdminGateState();}
class _AdminGateState extends State<AdminGate>{bool loading=true,ok=false;@override void initState(){super.initState();check();}Future<void> check()async{try{final u=supabase.auth.currentUser;if(u!=null){final p=await supabase.from('profiles').select('role').eq('id',u.id).maybeSingle();ok=p?['role']=='admin';}}finally{if(!ok)await supabase.auth.signOut();if(mounted)setState(()=>loading=false);}}@override Widget build(BuildContext c)=>loading?const Scaffold(body:Center(child:CircularProgressIndicator())):ok?const AdminPanel():Scaffold(appBar:AppBar(),body:Center(child:Column(mainAxisSize:MainAxisSize.min,children:[const Text('এই অ্যাকাউন্টে Admin access নেই'),FilledButton(onPressed:()=>Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>const AdminLogin()),(_)=>false),child:const Text('Back to login'))])));}
class AdminPanel extends StatefulWidget{const AdminPanel({super.key});@override State<AdminPanel> createState()=>_AdminPanelState();}
class _AdminPanelState extends State<AdminPanel>{int tab=0;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Task Earn Admin'),actions:[IconButton(onPressed:()async{await supabase.auth.signOut();if(mounted)Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>const AdminLogin()),(_)=>false);},icon:const Icon(Icons.logout))]),body:[const TasksTab(),const SubmissionsTab(),const WithdrawalsTab()][tab],bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const[NavigationDestination(icon:Icon(Icons.assignment),label:'Tasks'),NavigationDestination(icon:Icon(Icons.fact_check),label:'Submissions'),NavigationDestination(icon:Icon(Icons.payments),label:'Withdrawals')]));}
class TasksTab extends StatefulWidget{const TasksTab({super.key});@override State<TasksTab> createState()=>_TasksTabState();}
class _TasksTabState extends State<TasksTab>{List<Map<String,dynamic>> rows=[];bool loading=true;@override void initState(){super.initState();load();}Future<void> load()async{try{final d=await supabase.from('tasks').select().order('created_at',ascending:false);if(mounted)setState(()=>rows=List<Map<String,dynamic>>.from(d));}finally{if(mounted)setState(()=>loading=false);}}Future<void> edit([Map<String,dynamic>? t])async{final title=TextEditingController(text:t?['title']?.toString()??'');final desc=TextEditingController(text:t?['description']?.toString()??'');final reward=TextEditingController(text:t?['reward']?.toString()??'');final max=TextEditingController(text:t?['max_submissions']?.toString()??'');bool active=t?['is_active']??true;final yes=await showDialog<bool>(context:context,builder:(x)=>StatefulBuilder(builder:(x,setD)=>AlertDialog(title:Text(t==null?'Create Task':'Edit Task'),content:SingleChildScrollView(child:Column(children:[TextField(controller:title,decoration:const InputDecoration(labelText:'Title')),TextField(controller:desc,maxLines:4,decoration:const InputDecoration(labelText:'Instructions')),TextField(controller:reward,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Reward')),TextField(controller:max,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Max submissions')),SwitchListTile(value:active,onChanged:(v)=>setD(()=>active=v),title:const Text('Active'))])),actions:[TextButton(onPressed:()=>Navigator.pop(x,false),child:const Text('Cancel')),FilledButton(onPressed:()=>Navigator.pop(x,true),child:const Text('Save'))])));if(yes!=true)return;final data={'title':title.text.trim(),'description':desc.text.trim(),'reward':double.tryParse(reward.text)??0,'max_submissions':int.tryParse(max.text),'is_active':active};if(t==null){await supabase.from('tasks').insert(data);}else{await supabase.from('tasks').update(data).eq('id',t['id']);}await load();}@override Widget build(BuildContext c)=>loading?const Center(child:CircularProgressIndicator()):Scaffold(body:RefreshIndicator(onRefresh:load,child:ListView.builder(itemCount:rows.length,itemBuilder:(c,i){final r=rows[i];return ListTile(title:Text(r['title'].toString()),subtitle:Text('৳${r['reward']} • ${r['is_active']==true?'Active':'Inactive'}'),onTap:()=>edit(r));})),floatingActionButton:FloatingActionButton(onPressed:()=>edit(),child:const Icon(Icons.add)));}
class SubmissionsTab extends StatefulWidget{const SubmissionsTab({super.key});@override State<SubmissionsTab> createState()=>_SubmissionsTabState();}
class _SubmissionsTabState extends State<SubmissionsTab>{List<Map<String,dynamic>> rows=[];bool loading=true;@override void initState(){super.initState();load();}Future<void> load()async{try{final d=await supabase.from('task_submissions').select('id,user_id,proof,status,reward_amount,created_at,tasks(title)').order('created_at',ascending:false);if(mounted)setState(()=>rows=List<Map<String,dynamic>>.from(d));}finally{if(mounted)setState(()=>loading=false);}}Future<void> review(Map<String,dynamic> r,bool yes)async{await supabase.rpc(yes?'approve_task_submission':'reject_task_submission',params:{'p_submission_id':r['id'],'p_note':null});await load();}@override Widget build(BuildContext c)=>loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:load,child:ListView.builder(itemCount:rows.length,itemBuilder:(c,i){final r=rows[i];return Card(child:ListTile(title:Text((r['tasks']?['title']??'Task').toString()),subtitle:Text('Proof: ${r['proof']}\nReward: ৳${r['reward_amount']}\nStatus: ${r['status']}'),isThreeLine:true,trailing:r['status']=='pending'?Wrap(children:[IconButton(onPressed:()=>review(r,false),icon:const Icon(Icons.close)),IconButton(onPressed:()=>review(r,true),icon:const Icon(Icons.check))]):null));}));}
class WithdrawalsTab extends StatefulWidget{const WithdrawalsTab({super.key});@override State<WithdrawalsTab> createState()=>_WithdrawalsTabState();}
class _WithdrawalsTabState extends State<WithdrawalsTab>{List<Map<String,dynamic>> rows=[];bool loading=true;@override void initState(){super.initState();load();}Future<void> load()async{try{final d=await supabase.from('withdrawal_requests').select().order('created_at',ascending:false);if(mounted)setState(()=>rows=List<Map<String,dynamic>>.from(d));}finally{if(mounted)setState(()=>loading=false);}}Future<void> review(Map<String,dynamic> r,bool yes)async{await supabase.rpc('review_withdrawal',params:{'p_withdrawal_id':r['id'],'p_approve':yes,'p_note':null});await load();}@override Widget build(BuildContext c)=>loading?const Center(child:CircularProgressIndicator()):RefreshIndicator(onRefresh:load,child:ListView.builder(itemCount:rows.length,itemBuilder:(c,i){final r=rows[i];return Card(child:ListTile(title:Text('${r['method'].toString().toUpperCase()} • ৳${r['amount']}'),subtitle:Text('${r['account_number']}\nStatus: ${r['status']}'),trailing:r['status']=='pending'?Wrap(children:[IconButton(onPressed:()=>review(r,false),icon:const Icon(Icons.close)),IconButton(onPressed:()=>review(r,true),icon:const Icon(Icons.check))]):null));}));}
